<?php

declare(strict_types=1);

use Aheadworks\Rbslider\Block\Banner; // Banner block class
use Magento\Framework\Escaper; // Escaper for HTML

/** @var Banner $block */
/** @var Escaper $escaper */

?>



<script>
    'use strict';

    function initAwRbslider(config) {
        return {

            /**
             * Object.assign is used to override default values be provided, simple object destructuring can be used here too, but not all browsers that use hyva support it.
             */
            options: Object.assign({
                autoplay: true,
                pauseTimeBetweenTransitions: 3000,
                slideTransitionSpeed: 500,
                isStopAnimationMouseOnBanner: true,
                animation: 'fade',
                isRandomOrderImage: false,
                sliderListSelector: '.uk-slideshow',
                sliderItemSelector: '.aw-rbslider-item'
            }, config),

            slideshow: {
                options: {}
            },

            /**
             * Initialize widget
             */
            init() {

                /*if (this.options.isRandomOrderImage) {
                    this._randomSort();
                }*/
                // UIkit.on('init.uk.component', (e, name, data) => {
                //     if (name === 'slideshow') {
                //         this.loadSlides(data);
                //     }
                // });

                // const slideshow = UIkit.slideshow(this.$el, {
                //     autoplay: this.options.autoplay,
                //     autoplayInterval: this.options.pauseTimeBetweenTransitions,
                //     duration: this.options.slideTransitionSpeed,
                //     pauseOnHover: this.options.isStopAnimationMouseOnBanner,
                //     animation: this.options.animation
                // });
                // Rewrite slideshow resize method
                //this.slideshow.resize = () => this.resizeBanner(this,this.$el);

                // Disable stop animation, if click on slide navigaton or dot navigation
                // this.element.on('click.uk.slideshow', '[data-uk-slideshow-item]', function(e) {
                //     if (this.slideshow.options.autoplay) {
                //         this.slideshow.start();
                //     }
                // });

                //above code in js(which is in jquery)
                // Array.from(this.$el.querySelectorAll('[data-uk-slideshow-item]')).map(item => {
                //     item.addEventListener('click.uk.slideshow-item', (e) => {
                //         if (slideshow.options.autoplay) {
                //             slideshow.start();
                //         }
                //     });
                // });



                // Slideshow paused, if mouse cursor on slide navigaton or dot navigation
                // this.element.on({
                //     mouseenter: function() {
                //         if (slideshow.options.pauseOnHover) {
                //             slideshow.hovering = true;
                //         }
                //     },
                //     mouseleave: function() {
                //         slideshow.hovering = false;
                //     }
                // }, '.uk-dotnav, .uk-slidenav');

                //this load file only when banner is in viewport, this is vanilla js
                // const observer = new IntersectionObserver((entries) => {
                //     if (entries[0].isIntersecting) {
                //         this.initSlider();
                //         observer.disconnect();
                //     }
                // });
                // observer.observe(this.$el);


                if (this.options.bannerSchedule.length > 0) {
                    if (!this.timeValidator([this.options.bannerSchedule[0]])) {
                        this.delayedUpdate(this.options.bannerSchedule[0]);
                    }
                    if (this.timeValidator(this.options.bannerSchedule)) {
                        this.sendRequest(this.options.bannerId);
                    }
                }
            },

            initSlider() {
                // Prevent duplicate loads
                if (window.awRbsliderCheck === 'loading' || window.awRbsliderCheck === 'loaded') {
                    return;
                }

                window.awRbsliderCheck = 'loading';

                const script = document.createElement('script');
                script.src = `<?= $escaper->escapeJs($block->getViewFileUrl("Humcommerce_RbsliderHyvacompat/js/components/slideshow.js")) ?>`;

                script.onload = () => {
                    console.log('RbsliderHyvacompat slideshow script loaded');
                    window.awRbsliderCheck = 'loaded';
                };

                script.onerror = () => {
                    console.error('Failed to load RbsliderHyvacompat slideshow script');
                    window.awRbsliderCheck = undefined; // allow retry if needed
                };

                document.head.appendChild(script);
            },

            pauseOnEnter() {
                if (this.slideshow.options.pauseOnHover) {
                    this.slideshow.hovering = true;
                }
            },

            resumeOnLeave() {
                this.slideshow.hovering = false;
            },

            /**
             * Recalculate the width and height of the banner
             */
            resizeBanner(slideshow, componentRoot) {
                const mainContent = componentRoot.closest('#maincontent, .page-wrapper');

                let width,
                    height = slideshow.options.height;

                // Recalculate width
                if (slideshow.slides.length) {
                    width = slideshow.slides[0].querySelector('img.aw-rbslider__img').naturalWidth;
                }

                if (mainContent) {
                    if (mainContent.getBoundingClientRect().width < width) {
                        width = mainContent.getBoundingClientRect().width;
                    }
                    componentRoot.style.width = width + 'px';
                }
                // else if (document.querySelector('.page-wrapper')) {
                //     // AW RBSlider compatibility
                //     const containerBox = document.querySelector('.page-wrapper').getBoundingClientRect();

                //     const containerWidth = Math.floor(containerBox.width * 0.7);

                //     if (containerWidth < width) {
                //         width = containerWidth;
                //     }
                //     componentRoot.style.width = width + 'px';
                // }
                // Recalculate height
                if (slideshow.options.height === 'auto' && slideshow.slides.length) {
                    slideshow.slides.style.height = '';

                    height = slideshow.slides[0].getBoundingClientRect.height;

                    slideshow.container.style.height = height + 'px';

                    slideshow.slides.map(slide => {
                        slide.style.height = height + 'px';
                        slide.style.position = 'absolute';
                    });
                }
            },

            /**
             * Lazy load slides
             */
            loadSlides(slideshow) {
                slideshow.slides.each((index, slideElem) => {
                    if (index) {
                        const slideImg = slideElem.querySelector('img.aw-rbslider__img');
                        if (slideImg && slideImg.dataset.src) {
                            slideImg.addEventListener('load', () => {
                                slideImg.classList.add('is-loaded');
                            });
                            slideImg.src = slideImg.dataset.src;
                            slideImg.removeAttribute('data-src');
                        }
                    }
                });
            },

            /**
             * Compare current time with schedule
             *
             * @param schedule
             */
            timeValidator(schedule) {
                const currentDateMinute = Date.now() / 1000 / 60;
                let isValid = false;

                schedule.forEach(item => {
                    if (currentDateMinute === new Date(item).getTime() / 1000 / 60) {
                        isValid = true;
                    }
                });

                return isValid;
            },

            /**
             * Send request for clean banner cache
             *
             * @param bannerId
             */
            sendRequest(bannerId) {
                fetch(this.options.cacheCleanUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        bannerId
                    })
                });
            },

            /**
             * Schedule call to sendRequest for future time
             *
             * @param futureTime
             */
            delayedUpdate(futureTime) {

                const currentDateMinute = Date.now() / 1000 / 60;

                const interval = (new Date(futureTime).getTime() / 1000 / 60) - currentDateMinute;

                if (interval > 0) {
                    setTimeout(() => this.sendRequest(self.options.bannerId), interval)
                }
            },

            /**
             * Random sort
             * @private
             */
            _randomSort() {
                const sliderListSelector = this.options.sliderListSelector,
                    sliderItemSelector = this.options.sliderItemSelector;

                this.$el.querySelector(sliderListSelector)
                    .innerHtml = Array.from(this.$el.querySelectorAll(sliderListSelector + ' ' + sliderItemSelector).sort(() => {
                        return Math.random() - 0.5;
                    })).map(item => item.outerHtml).join('');
            }
        };
    }
</script>




<?php if ($bannersBlock = $block->getBlocks()): ?> <!-- Check if banner blocks exist -->
    <?php foreach ($bannersBlock as $bannerBlock) : ?> <!-- Loop banner blocks -->
        <?php
        $dotNavItems = '';
        $slideCounter = 1;
        $sliderConfig = $block->getBannerMageInitParams($bannerBlock)['awRbslider'];
        ?>
        <div

            x-data='initAwRbslider(<?= /* @noEscape */ $block->jsonEncode($sliderConfig) ?>)'

            x-init='init()'

            x-intersect.once="initSlider()"

            data-aw-rbslider-banner-id='<?= /* @noEscape */ $bannerBlock->getBanner()->getId(); ?>'
            class="aw-rbslider-container uk-slidenav-position"> <!-- data-mage-inti imports the js function along with configuration values from banner.php -->
            <div class="uk-slideshow uk-overlay-active">
                <?php foreach ($bannerBlock->getSlides() as $key => $slide) : ?>
                    <div class="aw-rbslider-item">
                        <div class="aw-rbslider-img-wrapper">
                            <picture>
                                <source media="(max-width: 480px)" srcset="<?= /* @noEscape */ $block->getSlideMobileImgUrl($slide) ?>"
                                    class="aw-rbslider__img  <?= $slideCounter === 1 ? 'is-loaded' : '' ?>"
                                    <?= $slideCounter !== 1 ? 'data-' : '' ?>
                                    title="<?= $escaper->escapeHtml($slide->getImgTitle()) ?>" />
                                <img class="aw-rbslider__img  <?= $slideCounter === 1 ? 'is-loaded' : '' ?>"
                                    <?= $slideCounter !== 1 ? 'data-' : '' ?>src="<?= /* @noEscape */ $block->getSlideImgUrl($slide) ?>"
                                    title="<?= $escaper->escapeHtml($slide->getImgTitle()) ?>"
                                    alt="<?= $escaper->escapeHtml($slide->getImgAlt()) ?>" />
                            </picture>
                            <?php if ($slide->getUrl()): ?>
                                <?php
                                $target = $slide->getIsOpenUrlInNewWindow() ? 'target="_blank"' : '';
                                $nofollow = $slide->getIsAddNofollowToUrl() ? 'rel="nofollow"' : '';
                                ?>
                                <a href="<?= /* @noEscape */ $slide->getUrl() ?>"
                                    class="aw-rbslider-img-url"
                                    data-mage-init='<?= /* @noEscape */ $block->jsonEncode($block->getSendClickStatisticsMageInitParams($bannerBlock->getBanner(), $slide)) ?>'
                                    <?= /* @noEscape */ $target ?>
                                    <?= /* @noEscape */ $nofollow ?>></a>
                            <?php endif; ?>
                            <?php if ($content = $slide->getContent()): ?>
                                <div class="aw-rbslider-content-wrapper uk-overlay-panel uk-flex uk-flex-center uk-flex-middle uk-text-center">
                                    <div>
                                        <?= /* @noEscape */ $content ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php $dotNavItems .= '<li data-uk-slideshow-item="' . $key . '"

                    x-on:[click.uk.slideshow]="slideshow.options.autoplay && slideshow.start()"

                    ><a href="#"></a></li>' ?>
                    <?php $slideCounter++; ?>
                <?php endforeach; ?> <!-- Loop slides -->
            </div>
            <?php if (count($bannerBlock->getSlides()) > 1): ?> <!-- If more than 1 slide, show nav -->
                <?php if ($bannerBlock->getBanner()->getDisplayArrows()) : ?>
                    <a href="#"
                        class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous"

                        @mouseenter="pauseOnEnter"

                        @mouseleave="resumeOnLeave"

                        x-on:[click.uk.slideshow]="slideshow.options.autoplay && slideshow.start()"

                        data-uk-slideshow-item="previous">
                        <span class="visually-hidden"><?= $escaper->escapeHtml(__('Show previous slide')) ?></span>
                    </a>
                    <a href="#"
                        class="uk-slidenav uk-slidenav-contrast uk-slidenav-next"

                        @mouseenter="pauseOnEnter"

                        @mouseleave="resumeOnLeave"

                        x-on:[click.uk.slideshow]="slideshow.options.autoplay && slideshow.start()"

                        data-uk-slideshow-item="next">
                        <span class="visually-hidden"><?= $escaper->escapeHtml(__('Show next slide')) ?></span>
                    </a>
                <?php endif; ?>
                <?php if ($bannerBlock->getBanner()->getDisplayBullets()) : ?>
                    <ul class="uk-dotnav uk-dotnav-contrast uk-position-bottom uk-flex-center"

                        @mouseenter="pauseOnEnter"

                        @mouseleave="resumeOnLeave">
                        <?= /* @noEscape */ $dotNavItems ?>
                    </ul>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>